----récupère toutes les SKUS achetés dans chaque saison
WITH saison AS (
SELECT
	CASE 
		WHEN LEFT(trim(so.reference),
		4) = 'AH23' THEN 'AH23'
		WHEN LEFT(trim(so.reference),
		4) = 'PE23' THEN 'PE23'
		WHEN LEFT(trim(so.reference),
		4) = 'AH22' THEN 'AH22'
		WHEN LEFT(trim(so.reference),
		4) = 'PE22' THEN 'PE22'
		WHEN LEFT(trim(so.reference),
		4) = 'AH21' THEN 'AH21'
		WHEN LEFT(trim(so.reference),
		4) = 'PE21' THEN 'PE21'
		WHEN LEFT(trim(so.reference),
		3) = 'A24' THEN 'AH24'
		WHEN LEFT(trim(so.reference),
		3) = 'P24' THEN 'PE24'
		WHEN LEFT(trim(so.reference),
		3) = 'A23' THEN 'AH23'
		WHEN LEFT(trim(so.reference),
		3) = 'P23' THEN 'PE23'
		WHEN LEFT(trim(so.reference),
		3) = 'A22' THEN 'AH22'
		WHEN LEFT(trim(so.reference),
		3) = 'P22' THEN 'PE22'
		WHEN LEFT(trim(so.reference),
		3) = 'A21' THEN 'AH21'
		WHEN LEFT(trim(so.reference),
		3) = 'P21' THEN 'PE21'
		WHEN LEFT(trim(so.reference),
		3) = 'A20' THEN 'AH20'
		WHEN LEFT(trim(so.reference),
		3) = 'P20' THEN 'PE20'
		WHEN LEFT(trim(so.reference),
		3) = 'A19' THEN 'AH19'
		WHEN LEFT(trim(so.reference),
		3) = 'P19' THEN 'PE19'
		WHEN LEFT(trim(so.reference),
		3) = 'A18' THEN 'AH18'
		WHEN LEFT(trim(so.reference),
		3) = 'P18' THEN 'PE18'
		WHEN LEFT(trim(so.reference),
		3) = 'A17' THEN 'AH17'
		WHEN LEFT(trim(so.reference),
		3) = 'P17' THEN 'PE17'
		ELSE NULL
	END AS s,
	sod.declinaison_id,
	d.id_product AS pid,
	d.reference,
	so.reference
FROM
	smallable2_descriptor.supply_order so
INNER JOIN smallable2_descriptor.supply_order_detail sod ON
	sod.supply_order_id = so.id
INNER JOIN smallable2_descriptor.declinaison d ON
	sod.declinaison_id = d.id 
	),
----- stock à date ----
stock_n AS (
SELECT
	bs.sku_id AS s,
	sum(CASE WHEN bs.quantity_type_id = 1 THEN bs.stock_delta ELSE 0 END) -
	sum(CASE WHEN bs.quantity_type_id IN (4, 5, 6) THEN bs.stock_delta ELSE 0 END) AS stock_n
FROM
	smallable2_datawarehouse.b_stocks bs
GROUP BY
	s),
----- stocks n-1 -----
stock_n1 AS (
SELECT
	bs.sku_id AS s,
	sum(CASE WHEN bs.quantity_type_id = 1 THEN bs.stock_delta ELSE 0 END) -
	sum(CASE WHEN bs.quantity_type_id IN (4, 5, 6) THEN bs.stock_delta ELSE 0 END) AS stock_n1
FROM
	smallable2_datawarehouse.b_stocks bs
WHERE
	bs.ref_date < date_sub(YEAR,
	1,
	today())
GROUP BY
	s)
------------------  REQUÊTE    ------------------
SELECT
	v.personne,
	v.marque,
	v.buyer,
	v.univers,
	s.stock_pe22_perm_valo + v.camv_pe22_perm AS "Dépenses PE22 Perm",
	s.stock_pe22_saiso_valo + v.camv_pe22_saiso AS "Dépenses PE22 Saiso",
	v.vn_pe22_perm AS "VN PE22 Perm",
	v.vn_pe22_saiso AS "VN PE22 Saiso",
	v.ca_pe22_perm AS "CA PE22 Perm",
	v.ca_pe22_saiso AS "CA PE22 Saiso",
	v.camv_pe22_perm AS "CAMV PE22 Perm",
	v.camv_pe22_saiso AS "CAMV PE22 Saiso",
	v.marge_pe22_perm AS "Marge PE22 Perm",
	v.marge_pe22_saiso AS "Marge PE22 Saiso",
	s.stock_pe22_perm AS "Stock PE22 Perm (Qté)",
	s.stock_pe22_saiso AS "Stock PE22 Saiso (Qté)",
	s.stock_pe22_perm_valo AS "Stock PE22 Perm (Valo prix d'achat)",
	s.stock_pe22_saiso_valo AS "Stock PE22 Saiso (Valo prix d'achat)",
	s.stock_pe23_perm_valo + v.camv_PE23_perm AS "Dépenses PE23 Perm",
	s.stock_pe23_saiso_valo + v.camv_PE23_saiso AS "Dépenses PE23 Saiso",
	v.vn_PE23_perm AS "VN PE23 Perm",
	v.vn_PE23_saiso AS "VN PE23 Saiso",
	v.ca_PE23_perm AS "CA PE23 Perm",
	v.ca_PE23_saiso AS "CA PE23 Saiso",
	v.camv_PE23_perm AS "CAMV PE23 Perm",
	v.camv_PE23_saiso AS "CAMV PE23 Saiso",
	v.marge_PE23_perm AS "Marge PE23 Perm",
	v.marge_PE23_saiso AS "Marge PE23 Saiso",
	s.stock_pe23_perm AS "Stock PE23 Perm (Qté)",
	s.stock_pe23_saiso AS "Stock PE23 Saiso (Qté)",
	s.stock_pe23_perm_valo AS "Stock PE23 Perm (Valo prix d'achat)",
	s.stock_pe23_saiso_valo AS "Stock PE23 Saiso (Valo prix d'achat)"
FROM
	----------- sous requête partie ventes ----------
   (
	SELECT
		bs.cible AS personne,
		bp.brand_name AS marque,
		CASE
			WHEN bp.brand_id = 629 THEN 'Acheteur.se Junior Accessoires'
			WHEN bp.brand_id = 623 THEN 'Pauline'
			WHEN bp.brand_id = 1970 THEN 'Emilie'
			WHEN bp.brand_id = 2109 THEN 'Lucie'
			WHEN bp.brand_id = 1702 THEN 'Emilie'
			WHEN bp.brand_id = 1257
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 1257
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 696 THEN 'Iris'
				WHEN bp.brand_id = 558
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 558
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 558
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1593 THEN 'Emilie'
				WHEN bp.brand_id = 1999 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2080 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1986 THEN 'Emilie'
				WHEN bp.brand_id = 1482 THEN 'Béatrice'
				WHEN bp.brand_id = 1741 THEN 'Léa'
				WHEN bp.brand_id = 210
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 210
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 210
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 210
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1097 THEN 'Léa'
				WHEN bp.brand_id = 1948 THEN 'Elodie'
				WHEN bp.brand_id = 1931 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 950 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1956 THEN 'Béatrice'
				WHEN bp.brand_id = 1636 THEN 'Alice'
				WHEN bp.brand_id = 1968 THEN 'Elodie'
				WHEN bp.brand_id = 1845
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 1845
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1845
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1642 THEN 'Béatrice'
				WHEN bp.brand_id = 1087
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1087
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 2044 THEN 'Alice'
				WHEN bp.brand_id = 627 THEN 'Alice'
				WHEN bp.brand_id = 1966 THEN 'Elodie'
				WHEN bp.brand_id = 1477 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 935 THEN 'Emilie'
				WHEN bp.brand_id = 1706 THEN 'Elodie'
				WHEN bp.brand_id = 217 THEN 'Iris'
				WHEN bp.brand_id = 1448 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1427 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1526 THEN 'Béatrice'
				WHEN bp.brand_id = 1411
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1411
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1716 THEN 'Serpil'
				WHEN bp.brand_id = 1997 THEN 'Lucie'
				WHEN bp.brand_id = 1581 THEN 'Serpil'
				WHEN bp.brand_id = 1401 THEN 'Alice'
				WHEN bp.brand_id = 1698 THEN 'Serpil'
				WHEN bp.brand_id = 1413
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1413
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1413
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1492 THEN 'Serpil'
				WHEN bp.brand_id = 1745 THEN 'Léa'
				WHEN bp.brand_id = 147
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 147
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 1606 THEN 'Béatrice'
				WHEN bp.brand_id = 2034 THEN 'Marlène'
				WHEN bp.brand_id = 176 THEN 'Marlène'
				WHEN bp.brand_id = 1727 THEN 'Lucie'
				WHEN bp.brand_id = 710 THEN 'Alice'
				WHEN bp.brand_id = 2087 THEN 'Marlène'
				WHEN bp.brand_id = 1877 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1611 THEN 'Marlène'
				WHEN bp.brand_id = 1253 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2056 THEN 'Serpil'
				WHEN bp.brand_id = 2040
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 2040
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1238 THEN 'Léa'
				WHEN bp.brand_id = 1933 THEN 'Serpil'
				WHEN bp.brand_id = 1337 THEN 'Lucie'
				WHEN bp.brand_id = 1544 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1973 THEN 'Iris'
				WHEN bp.brand_id = 1825 THEN 'Emilie'
				WHEN bp.brand_id = 1896 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2086 THEN 'Marlène'
				WHEN bp.brand_id = 398 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1483 THEN 'Elodie'
				WHEN bp.brand_id = 63
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 63
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 175 THEN 'Alice'
				WHEN bp.brand_id = 1694 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2088 THEN 'Lucie'
				WHEN bp.brand_id = 1969 THEN 'Béatrice'
				WHEN bp.brand_id = 625
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 625
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1717 THEN 'Serpil'
				WHEN bp.brand_id = 1683 THEN 'Léa'
				WHEN bp.brand_id = 1607
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1607
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 75
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 75
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1547 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1343 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1952 THEN 'Léa'
				WHEN bp.brand_id = 1055 THEN 'Marlène'
				WHEN bp.brand_id = 1629 THEN 'Lucie'
				WHEN bp.brand_id = 1017 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1511 THEN 'Marlène'
				WHEN bp.brand_id = 1164 THEN 'Pauline'
				WHEN bp.brand_id = 405 THEN 'Marlène'
				WHEN bp.brand_id = 2042 THEN 'Lucie'
				WHEN bp.brand_id = 1657 THEN 'Béatrice'
				WHEN bp.brand_id = 2021 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1540 THEN 'Lucie'
				WHEN bp.brand_id = 1853 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 387 THEN 'Pauline'
				WHEN bp.brand_id = 1847 THEN 'Béatrice'
				WHEN bp.brand_id = 2051 THEN 'Iris'
				WHEN bp.brand_id = 1906 THEN 'Emilie'
				WHEN bp.brand_id = 386 THEN 'Iris'
				WHEN bp.brand_id = 1738 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 399
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 399
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 399
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1104 THEN 'Iris'
				WHEN bp.brand_id = 223 THEN 'Marlène'
				WHEN bp.brand_id = 2058 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1501 THEN 'Serpil'
				WHEN bp.brand_id = 1975 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1761
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1761
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 1423 THEN 'Serpil'
				WHEN bp.brand_id = 1932 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1132 THEN 'Léa'
				WHEN bp.brand_id = 1672 THEN 'Béatrice'
				WHEN bp.brand_id = 1512 THEN 'Emilie'
				WHEN bp.brand_id = 346
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 346
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 346
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1848 THEN 'Béatrice'
				WHEN bp.brand_id = 1347 THEN 'Alice'
				WHEN bp.brand_id = 459 THEN 'Alice'
				WHEN bp.brand_id = 2050
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 2050
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 2050
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1892 THEN 'Emilie'
				WHEN bp.brand_id = 1751 THEN 'Alice'
				WHEN bp.brand_id = 1574 THEN 'Béatrice'
				WHEN bp.brand_id = 2006 THEN 'Serpil'
				WHEN bp.brand_id = 2029 THEN 'Iris'
				WHEN bp.brand_id = 1977 THEN 'Léa'
				WHEN bp.brand_id = 1852 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2064 THEN 'Alice'
				WHEN bp.brand_id = 2108 THEN 'Lucie'
				WHEN bp.brand_id = 1491 THEN 'Serpil'
				WHEN bp.brand_id = 2012 THEN 'Emilie'
				WHEN bp.brand_id = 1893 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1762 THEN 'Emilie'
				WHEN bp.brand_id = 1553 THEN 'Léa'
				WHEN bp.brand_id = 1637 THEN 'Emilie'
				WHEN bp.brand_id = 385 THEN 'Iris'
				WHEN bp.brand_id = 1714 THEN 'Serpil'
				WHEN bp.brand_id = 1955 THEN 'Léa'
				WHEN bp.brand_id = 1360 THEN 'Emilie'
				WHEN bp.brand_id = 1587
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1587
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1620 THEN 'Léa'
				WHEN bp.brand_id = 487
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 487
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 496
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 496
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1894 THEN 'Emilie'
				WHEN bp.brand_id = 1426 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1612 THEN 'Serpil'
				WHEN bp.brand_id = 1720 THEN 'Serpil'
				WHEN bp.brand_id = 1898 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1541 THEN 'Anais'
				WHEN bp.brand_id = 1424
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1424
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1545 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1171 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1854 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1833 THEN 'Léa'
				WHEN bp.brand_id = 181
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 181
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1763 THEN 'Emilie'
				WHEN bp.brand_id = 2004 THEN 'Béatrice'
				WHEN bp.brand_id = 2090 THEN 'Marlène'
				WHEN bp.brand_id = 1403 THEN 'Iris'
				WHEN bp.brand_id = 1480 THEN 'Béatrice'
				WHEN bp.brand_id = 1495
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1495
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 2028 THEN 'Lucie'
				WHEN bp.brand_id = 1935 THEN 'Léa'
				WHEN bp.brand_id = 1679 THEN 'Marlène'
				WHEN bp.brand_id = 215 THEN 'Iris'
				WHEN bp.brand_id = 1251 THEN 'Lucie'
				WHEN bp.brand_id = 501 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1596 THEN 'Emilie'
				WHEN bp.brand_id = 2057 THEN 'Lucie'
				WHEN bp.brand_id = 1827 THEN 'Serpil'
				WHEN bp.brand_id = 1568 THEN 'Elodie'
				WHEN bp.brand_id = 2060 THEN 'Marlène'
				WHEN bp.brand_id = 711 THEN 'Alice'
				WHEN bp.brand_id = 2073 THEN 'Emilie'
				WHEN bp.brand_id = 636
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 636
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 1167
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 1167
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1167
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1822 THEN 'Léa'
				WHEN bp.brand_id = 1976 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1733 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1476 THEN 'Léa'
				WHEN bp.brand_id = 1779 THEN 'Marlène'
				WHEN bp.brand_id = 1569 THEN 'Elodie'
				WHEN bp.brand_id = 369 THEN 'Marlène'
				WHEN bp.brand_id = 1421 THEN 'Léa'
				WHEN bp.brand_id = 1524 THEN 'Emilie'
				WHEN bp.brand_id = 1570 THEN 'Léa'
				WHEN bp.brand_id = 1040 THEN 'Alice'
				WHEN bp.brand_id = 1988 THEN 'Marlène'
				WHEN bp.brand_id = 225 THEN 'Alice'
				WHEN bp.brand_id = 1435 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1304 THEN 'Iris'
				WHEN bp.brand_id = 1613 THEN 'Serpil'
				WHEN bp.brand_id = 933 THEN 'Marlène'
				WHEN bp.brand_id = 1473 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1897 THEN 'Emilie'
				WHEN bp.brand_id = 735 THEN 'Emilie'
				WHEN bp.brand_id = 1855 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 143
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 143
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 143
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 395 THEN 'Alice'
				WHEN bp.brand_id = 1393 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 749 THEN 'Lucie'
				WHEN bp.brand_id = 1749 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2043 THEN 'Serpil'
				WHEN bp.brand_id = 1018 THEN 'Emilie'
				WHEN bp.brand_id = 2071 THEN 'Emilie'
				WHEN bp.brand_id = 2033
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 2033
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 475 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1978
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1978
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 2074 THEN 'Léa'
				WHEN bp.brand_id = 1628 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2000 THEN 'Lucie'
				WHEN bp.brand_id = 2059 THEN 'Lucie'
				WHEN bp.brand_id = 2053 THEN 'Serpil'
				WHEN bp.brand_id = 833 THEN 'Serpil'
				WHEN bp.brand_id = 1137 THEN 'Elodie'
				WHEN bp.brand_id = 2107 THEN 'Marlène'
				WHEN bp.brand_id = 1677 THEN 'Lucie'
				WHEN bp.brand_id = 1341 THEN 'Marlène'
				WHEN bp.brand_id = 1752 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1743 THEN 'Léa'
				WHEN bp.brand_id = 1703 THEN 'Marlène'
				WHEN bp.brand_id = 1995 THEN 'Alice'
				WHEN bp.brand_id = 1972 THEN 'Iris'
				WHEN bp.brand_id = 891 THEN 'Iris'
				WHEN bp.brand_id = 1583
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1583
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 967 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1669 THEN 'Léa'
				WHEN bp.brand_id = 1993 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1723 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1484 THEN 'Béatrice'
				WHEN bp.brand_id = 1313 THEN 'Emilie'
				WHEN bp.brand_id = 966 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1127 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1979 THEN 'Léa'
				WHEN bp.brand_id = 473 THEN 'Iris'
				WHEN bp.brand_id = 452
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 452
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1216 THEN 'Emilie'
				WHEN bp.brand_id = 1903 THEN 'Lucie'
				WHEN bp.brand_id = 1912 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1857 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1412 THEN 'Emilie'
				WHEN bp.brand_id = 2054 THEN 'Serpil'
				WHEN bp.brand_id = 1747 THEN 'Léa'
				WHEN bp.brand_id = 1500
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1500
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1199 THEN 'Pauline'
				WHEN bp.brand_id = 1239 THEN 'Léa'
				WHEN bp.brand_id = 2077 THEN 'Elodie'
				WHEN bp.brand_id = 1355 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1907 THEN 'Emilie'
				WHEN bp.brand_id = 1094
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1094
				AND bs.cible = 'BB/Enf/Ado' THEN 'Léa'
				WHEN bp.brand_id = 858 THEN 'Marlène'
				WHEN bp.brand_id = 1764 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1520 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 961 THEN 'Elodie'
				WHEN bp.brand_id = 1617 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1737 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2005 THEN 'Serpil'
				WHEN bp.brand_id = 1990 THEN 'Emilie'
				WHEN bp.brand_id = 323 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1699 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1631 THEN 'Emilie'
				WHEN bp.brand_id = 1486 THEN 'Béatrice'
				WHEN bp.brand_id = 397 THEN 'Léa'
				WHEN bp.brand_id = 777 THEN 'Iris'
				WHEN bp.brand_id = 836 THEN 'Lucie'
				WHEN bp.brand_id = 1863 THEN 'Lucie'
				WHEN bp.brand_id = 599 THEN 'Iris'
				WHEN bp.brand_id = 1371 THEN 'Serpil'
				WHEN bp.brand_id = 1485 THEN 'Béatrice'
				WHEN bp.brand_id = 1356 THEN 'Léa'
				WHEN bp.brand_id = 1107 THEN 'Pauline'
				WHEN bp.brand_id = 2089 THEN 'Marlène'
				WHEN bp.brand_id = 2070 THEN 'Marlène'
				WHEN bp.brand_id = 906 THEN 'Iris'
				WHEN bp.brand_id = 1243 THEN 'Iris'
				WHEN bp.brand_id = 1496
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1496
				AND bs.cible = 'BB/Enf/Ado' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 66
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 66
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1252 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 442
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 442
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1334 THEN 'Marlène'
				WHEN bp.brand_id = 1690 THEN 'Marlène'
				WHEN bp.brand_id = 1226 THEN 'Léa'
				WHEN bp.brand_id = 191 THEN 'Lucie'
				WHEN bp.brand_id = 1362 THEN 'Béatrice'
				WHEN bp.brand_id = 1600 THEN 'Béatrice'
				WHEN bp.brand_id = 1168 THEN 'Lucie'
				WHEN bp.brand_id = 1964 THEN 'Elodie'
				WHEN bp.brand_id = 1147 THEN 'Béatrice'
				WHEN bp.brand_id = 1293 THEN 'Iris'
				WHEN bp.brand_id = 1821 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1858 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2097 THEN 'Béatrice'
				WHEN bp.brand_id = 1363 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1638 THEN 'Emilie'
				WHEN bp.brand_id = 1784 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1765
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1765
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 747 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2091 THEN 'Elodie'
				WHEN bp.brand_id = 1283 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1229
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 1229
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 937 THEN 'Elodie'
				WHEN bp.brand_id = 753 THEN 'Lucie'
				WHEN bp.brand_id = 1335
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 1335
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1488 THEN 'Béatrice'
				WHEN bp.brand_id = 1876 THEN 'Iris'
				WHEN bp.brand_id = 1573 THEN 'Béatrice'
				WHEN bp.brand_id = 440 THEN 'Alice'
				WHEN bp.brand_id = 2061 THEN 'Alice'
				WHEN bp.brand_id = 1987 THEN 'Emilie'
				WHEN bp.brand_id = 1718 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2030 THEN 'Emilie'
				WHEN bp.brand_id = 1303 THEN 'Emilie'
				WHEN bp.brand_id = 1870
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1870
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1233 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1332 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1468 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1391 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 197 THEN 'Lucie'
				WHEN bp.brand_id = 1169
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1169
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1223 THEN 'Iris'
				WHEN bp.brand_id = 570
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 570
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1651 THEN 'Elodie'
				WHEN bp.brand_id = 1542 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1264 THEN 'Iris'
				WHEN bp.brand_id = 1160 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1963 THEN 'Lucie'
				WHEN bp.brand_id = 1425 THEN 'Marlène'
				WHEN bp.brand_id = 1159 THEN 'Elodie'
				WHEN bp.brand_id = 1546 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 800 THEN 'Iris'
				WHEN bp.brand_id = 1299 THEN 'Marlène'
				WHEN bp.brand_id = 1739 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 619
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 619
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 619
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 2105 THEN 'Emilie'
				WHEN bp.brand_id = 177 THEN 'Lucie'
				WHEN bp.brand_id = 1213 THEN 'Béatrice'
				WHEN bp.brand_id = 1726 THEN 'Béatrice'
				WHEN bp.brand_id = 2065 THEN 'Alice'
				WHEN bp.brand_id = 1740 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1849 THEN 'Béatrice'
				WHEN bp.brand_id = 716 THEN 'Lucie'
				WHEN bp.brand_id = 1766 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2027 THEN 'Lucie'
				WHEN bp.brand_id = 2075 THEN 'Anais'
				WHEN bp.brand_id = 1991 THEN 'Léa'
				WHEN bp.brand_id = 402
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 402
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 402
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 512
				AND bs.cible = 'Homme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 512
				AND bs.cible = 'BB/Enf/Ado' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1374 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1778 THEN 'Emilie'
				WHEN bp.brand_id = 2001 THEN 'Lucie'
				WHEN bp.brand_id = 511 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1828 THEN 'Serpil'
				WHEN bp.brand_id = 1639 THEN 'Emilie'
				WHEN bp.brand_id = 1829 THEN 'Serpil'
				WHEN bp.brand_id = 1433
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1433
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1715
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 1715
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1715
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1859 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1490 THEN 'Serpil'
				WHEN bp.brand_id = 1305 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 129 THEN 'Lucie'
				WHEN bp.brand_id = 1536 THEN 'Emilie'
				WHEN bp.brand_id = 1744 THEN 'Léa'
				WHEN bp.brand_id = 1984 THEN 'Serpil'
				WHEN bp.brand_id = 2038 THEN 'Elodie'
				WHEN bp.brand_id = 2035 THEN 'Marlène'
				WHEN bp.brand_id = 1634
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1634
				AND bs.cible = 'BB/Enf/Ado' THEN 'Léa'
				WHEN bp.brand_id = 1708 THEN 'Béatrice'
				WHEN bp.brand_id = 2024 THEN 'Léa'
				WHEN bp.brand_id = 1788 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1900 THEN 'Léa'
				WHEN bp.brand_id = 1640
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1640
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 1700
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1700
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1046
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 1046
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1046
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1985 THEN 'Emilie'
				WHEN bp.brand_id = 2069 THEN 'Marlène'
				WHEN bp.brand_id = 1957 THEN 'Béatrice'
				WHEN bp.brand_id = 377 THEN 'Alice'
				WHEN bp.brand_id = 1430 THEN 'Serpil'
				WHEN bp.brand_id = 1908
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1908
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 78
				AND bs.cible = 'Femme' THEN 'Pauline'
				WHEN bp.brand_id = 78
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1661 THEN 'Lucie'
				WHEN bp.brand_id = 79 THEN 'Alice'
				WHEN bp.brand_id = 1152 THEN 'Marlène'
				WHEN bp.brand_id = 1402
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1402
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1981 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1218 THEN 'Lucie'
				WHEN bp.brand_id = 1885 THEN 'Léa'
				WHEN bp.brand_id = 219 THEN 'Alice'
				WHEN bp.brand_id = 479 THEN 'Alice'
				WHEN bp.brand_id = 938 THEN 'Elodie'
				WHEN bp.brand_id = 2052 THEN 'Serpil'
				WHEN bp.brand_id = 1755 THEN 'Alice'
				WHEN bp.brand_id = 1775 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 832
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 832
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1674 THEN 'Anais'
				WHEN bp.brand_id = 313
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 313
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 313
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1294 THEN 'Marlène'
				WHEN bp.brand_id = 1665 THEN 'Béatrice'
				WHEN bp.brand_id = 1731 THEN 'Elodie'
				WHEN bp.brand_id = 2067 THEN 'Léa'
				WHEN bp.brand_id = 1652 THEN 'Serpil'
				WHEN bp.brand_id = 1416 THEN 'Serpil'
				WHEN bp.brand_id = 530 THEN 'Iris'
				WHEN bp.brand_id = 1713 THEN 'Serpil'
				WHEN bp.brand_id = 1954 THEN 'Léa'
				WHEN bp.brand_id = 1909 THEN 'Emilie'
				WHEN bp.brand_id = 1895 THEN 'Emilie'
				WHEN bp.brand_id = 1292 THEN 'Iris'
				WHEN bp.brand_id = 1350 THEN 'Lucie'
				WHEN bp.brand_id = 1098 THEN 'Emilie'
				WHEN bp.brand_id = 286 THEN 'Alice'
				WHEN bp.brand_id = 1867 THEN 'Lucie'
				WHEN bp.brand_id = 1575 THEN 'Béatrice'
				WHEN bp.brand_id = 1048 THEN 'Elodie'
				WHEN bp.brand_id = 1936 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1204 THEN 'Elodie'
				WHEN bp.brand_id = 1624 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1582 THEN 'Emilie'
				WHEN bp.brand_id = 732
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 732
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1539 THEN 'Emilie'
				WHEN bp.brand_id = 1095 THEN 'Léa'
				WHEN bp.brand_id = 708
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 708
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1242 THEN 'Emilie'
				WHEN bp.brand_id = 1768 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1843 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1502
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 1502
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1577 THEN 'Emilie'
				WHEN bp.brand_id = 1494
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1494
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1141 THEN 'Léa'
				WHEN bp.brand_id = 324 THEN 'Iris'
				WHEN bp.brand_id = 1983 THEN 'Léa'
				WHEN bp.brand_id = 1475 THEN 'Béatrice'
				WHEN bp.brand_id = 1735 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2055 THEN 'Serpil'
				WHEN bp.brand_id = 546 THEN 'Elodie'
				WHEN bp.brand_id = 1851
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1851
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1712 THEN 'Béatrice'
				WHEN bp.brand_id = 1911 THEN 'Emilie'
				WHEN bp.brand_id = 1958 THEN 'Alice'
				WHEN bp.brand_id = 1878 THEN 'Lucie'
				WHEN bp.brand_id = 85 THEN 'Lucie'
				WHEN bp.brand_id = 1992 THEN 'Léa'
				WHEN bp.brand_id = 1417 THEN 'Béatrice'
				WHEN bp.brand_id = 2002 THEN 'Lucie'
				WHEN bp.brand_id = 1901 THEN 'Léa'
				WHEN bp.brand_id = 1560 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 310 THEN 'Elodie'
				WHEN bp.brand_id = 319 THEN 'Lucie'
				WHEN bp.brand_id = 1344 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 270 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1054 THEN 'Marlène'
				WHEN bp.brand_id = 2098 THEN 'Béatrice'
				WHEN bp.brand_id = 320
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 320
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 320
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1891 THEN 'Emilie'
				WHEN bp.brand_id = 111 THEN 'Alice'
				WHEN bp.brand_id = 1474 THEN 'Béatrice'
				WHEN bp.brand_id = 1308 THEN 'Béatrice'
				WHEN bp.brand_id = 1194 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 199 THEN 'Lucie'
				WHEN bp.brand_id = 1846 THEN 'Béatrice'
				WHEN bp.brand_id = 2015 THEN 'Elodie'
				WHEN bp.brand_id = 1994 THEN 'Emilie'
				WHEN bp.brand_id = 1031 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1302 THEN 'Iris'
				WHEN bp.brand_id = 1138 THEN 'Marlène'
				WHEN bp.brand_id = 2096 THEN 'Emilie'
				WHEN bp.brand_id = 370 THEN 'Iris'
				WHEN bp.brand_id = 381 THEN 'Iris'
				WHEN bp.brand_id = 1884 THEN 'Serpil'
				WHEN bp.brand_id = 559 THEN 'Alice'
				WHEN bp.brand_id = 1728 THEN 'Lucie'
				WHEN bp.brand_id = 1135 THEN 'Elodie'
				WHEN bp.brand_id = 1860 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1982 THEN 'Léa'
				WHEN bp.brand_id = 1419
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1419
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1531 THEN 'Léa'
				WHEN bp.brand_id = 483 THEN 'Marlène'
				WHEN bp.brand_id = 303 THEN 'Alice'
				WHEN bp.brand_id = 1769
				AND bs.cible = 'Homme' THEN 'Alice'
				WHEN bp.brand_id = 1769
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 721 THEN 'Lucie'
				WHEN bp.brand_id = 1770 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2081 THEN 'Béatrice'
				WHEN bp.brand_id = 589 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1980 THEN 'Béatrice'
				WHEN bp.brand_id = 2078 THEN 'Marlène'
				WHEN bp.brand_id = 1214
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 1214
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 489
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 489
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 489
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1340 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1678 THEN 'Marlène'
				WHEN bp.brand_id = 1478 THEN 'Anais'
				WHEN bp.brand_id = 1704
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1704
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1861 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 404 THEN 'Alice'
				WHEN bp.brand_id = 1358 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1558 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 809 THEN 'Léa'
				WHEN bp.brand_id = 1013
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1013
				AND bs.cible = 'BB/Enf/Ado' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 893 THEN 'Lucie'
				WHEN bp.brand_id = 1450 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1864 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2092 THEN 'Elodie'
				WHEN bp.brand_id = 2039 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1989 THEN 'Lucie'
				WHEN bp.brand_id = 1721 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 336
				AND bs.cible = 'Homme' THEN 'Alice'
				WHEN bp.brand_id = 336
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1301 THEN 'Elodie'
				WHEN bp.brand_id = 1830 THEN 'Serpil'
				WHEN bp.brand_id = 1879 THEN 'Marlène'
				WHEN bp.brand_id = 2011 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1750 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1099 THEN 'Elodie'
				WHEN bp.brand_id = 262
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 262
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1841 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 180
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 180
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1719 THEN 'Serpil'
				WHEN bp.brand_id = 1359 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1705 THEN 'Alice'
				WHEN bp.brand_id = 1711 THEN 'Elodie'
				WHEN bp.brand_id = 1145 THEN 'Lucie'
				WHEN bp.brand_id = 1222 THEN 'Lucie'
				WHEN bp.brand_id = 1882 THEN 'Lucie'
				WHEN bp.brand_id = 2076 THEN 'Serpil'
				WHEN bp.brand_id = 1258 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1594 THEN 'Serpil'
				WHEN bp.brand_id = 1996 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1241 THEN 'Elodie'
				WHEN bp.brand_id = 857 THEN 'Lucie'
				WHEN bp.brand_id = 1691 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1011 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1187 THEN 'Serpil'
				WHEN bp.brand_id = 1794 THEN 'Marlène'
				WHEN bp.brand_id = 606 THEN 'Alice'
				WHEN bp.brand_id = 1525 THEN 'Anais'
				WHEN bp.brand_id = 1883 THEN 'Lucie'
				WHEN bp.brand_id = 1151 THEN 'Marlène'
				WHEN bp.brand_id = 1961 THEN 'Béatrice'
				WHEN bp.brand_id = 1664 THEN 'Léa'
			END AS buyer,
			bs.univers AS univers,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-10-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN bop.qty_ordered - bop.qty_canceled ELSE NULL END) AS vn_pe22_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-10-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN bop.qty_ordered - bop.qty_canceled ELSE NULL END) AS vn_pe22_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-10-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN bop.billing_product_ht / 100 ELSE NULL END) AS ca_pe22_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-10-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN bop.billing_product_ht / 100 ELSE NULL END) AS ca_pe22_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-11-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN (bop.billing_product_ht - bop.cost_product_ht) / 100 ELSE NULL END) AS marge_pe22_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-11-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN (bop.billing_product_ht - bop.cost_product_ht) / 100 ELSE NULL END) AS marge_pe22_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN bop.qty_ordered - bop.qty_canceled ELSE NULL END) AS vn_PE23_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN bop.qty_ordered - bop.qty_canceled ELSE NULL END) AS vn_PE23_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN bop.billing_product_ht / 100 ELSE NULL END) AS ca_PE23_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN bop.billing_product_ht / 100 ELSE NULL END) AS ca_PE23_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN (bop.billing_product_ht - bop.cost_product_ht) / 100 ELSE NULL END) AS marge_PE23_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN (bop.billing_product_ht - bop.cost_product_ht) / 100 ELSE NULL END) AS marge_PE23_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-10-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN bop.cost_product_ht / 100 ELSE NULL END) AS camv_pe22_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') AND bo.invoiced_at > '2021-10-16' AND bo.invoiced_at < date_sub(YEAR, 1, today()) THEN bop.cost_product_ht / 100 ELSE NULL END) AS camv_pe22_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN bop.cost_product_ht / 100 ELSE NULL END) AS camv_PE23_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bop.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') AND bo.invoiced_at > '2022-10-15' AND bo.invoiced_at < today() THEN bop.cost_product_ht / 100 ELSE NULL END) AS camv_PE23_saiso
			--,sum(CASE WHEN bop.product_id IN (SELECT pid FROM saison WHERE s != 'PE23') AND bo.invoiced_at > '2022-10-31' AND bo.invoiced_at < today() THEN bop.billing_product_ht / 100 ELSE NULL END) AS ca_PE23_anciens_produits
		FROM
			smallable2_datawarehouse.b_orders bo
		INNER JOIN smallable2_datawarehouse.b_order_products bop ON
			bo.order_id = bop.order_id
			AND bo.is_valid = 1
			AND bo.is_ca_net_ht_not_zero = 1
		INNER JOIN smallable2_datawarehouse.b_products bp ON
			bop.product_id = bp.product_id
		INNER JOIN smallable2_datawarehouse.b_skus bs ON
			bs.sku_id = bop.sku_id
		WHERE
			bp.sml_team = 'mode'
			AND bs.univers NOT IN ('Masques', 'na')
				AND bs.personne_ordre != 'na'
			GROUP BY
				personne,
				marque,
				buyer,
				univers
			ORDER BY
				vn_PE23_saiso DESC) v
	----------- sous requête partie stock ----------
LEFT JOIN (
	SELECT
		bs.cible AS personne,
		bp.brand_name AS marque,
		CASE
			WHEN bp.brand_id = 629 THEN 'Acheteur.se Junior Accessoires'
			WHEN bp.brand_id = 623 THEN 'Pauline'
			WHEN bp.brand_id = 1970 THEN 'Emilie'
			WHEN bp.brand_id = 2109 THEN 'Lucie'
			WHEN bp.brand_id = 1702 THEN 'Emilie'
			WHEN bp.brand_id = 1257
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 1257
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 696 THEN 'Iris'
				WHEN bp.brand_id = 558
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 558
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 558
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1593 THEN 'Emilie'
				WHEN bp.brand_id = 1999 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2080 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1986 THEN 'Emilie'
				WHEN bp.brand_id = 1482 THEN 'Béatrice'
				WHEN bp.brand_id = 1741 THEN 'Léa'
				WHEN bp.brand_id = 210
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 210
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 210
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 210
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1097 THEN 'Léa'
				WHEN bp.brand_id = 1948 THEN 'Elodie'
				WHEN bp.brand_id = 1931 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 950 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1956 THEN 'Béatrice'
				WHEN bp.brand_id = 1636 THEN 'Alice'
				WHEN bp.brand_id = 1968 THEN 'Elodie'
				WHEN bp.brand_id = 1845
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 1845
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1845
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1642 THEN 'Béatrice'
				WHEN bp.brand_id = 1087
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1087
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 2044 THEN 'Alice'
				WHEN bp.brand_id = 627 THEN 'Alice'
				WHEN bp.brand_id = 1966 THEN 'Elodie'
				WHEN bp.brand_id = 1477 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 935 THEN 'Emilie'
				WHEN bp.brand_id = 1706 THEN 'Elodie'
				WHEN bp.brand_id = 217 THEN 'Iris'
				WHEN bp.brand_id = 1448 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1427 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1526 THEN 'Béatrice'
				WHEN bp.brand_id = 1411
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1411
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1716 THEN 'Serpil'
				WHEN bp.brand_id = 1997 THEN 'Lucie'
				WHEN bp.brand_id = 1581 THEN 'Serpil'
				WHEN bp.brand_id = 1401 THEN 'Alice'
				WHEN bp.brand_id = 1698 THEN 'Serpil'
				WHEN bp.brand_id = 1413
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1413
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1413
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1492 THEN 'Serpil'
				WHEN bp.brand_id = 1745 THEN 'Léa'
				WHEN bp.brand_id = 147
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 147
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 1606 THEN 'Béatrice'
				WHEN bp.brand_id = 2034 THEN 'Marlène'
				WHEN bp.brand_id = 176 THEN 'Marlène'
				WHEN bp.brand_id = 1727 THEN 'Lucie'
				WHEN bp.brand_id = 710 THEN 'Alice'
				WHEN bp.brand_id = 2087 THEN 'Marlène'
				WHEN bp.brand_id = 1877 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1611 THEN 'Marlène'
				WHEN bp.brand_id = 1253 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2056 THEN 'Serpil'
				WHEN bp.brand_id = 2040
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 2040
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1238 THEN 'Léa'
				WHEN bp.brand_id = 1933 THEN 'Serpil'
				WHEN bp.brand_id = 1337 THEN 'Lucie'
				WHEN bp.brand_id = 1544 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1973 THEN 'Iris'
				WHEN bp.brand_id = 1825 THEN 'Emilie'
				WHEN bp.brand_id = 1896 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2086 THEN 'Marlène'
				WHEN bp.brand_id = 398 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1483 THEN 'Elodie'
				WHEN bp.brand_id = 63
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 63
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 175 THEN 'Alice'
				WHEN bp.brand_id = 1694 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2088 THEN 'Lucie'
				WHEN bp.brand_id = 1969 THEN 'Béatrice'
				WHEN bp.brand_id = 625
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 625
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1717 THEN 'Serpil'
				WHEN bp.brand_id = 1683 THEN 'Léa'
				WHEN bp.brand_id = 1607
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1607
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 75
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 75
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1547 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1343 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1952 THEN 'Léa'
				WHEN bp.brand_id = 1055 THEN 'Marlène'
				WHEN bp.brand_id = 1629 THEN 'Lucie'
				WHEN bp.brand_id = 1017 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1511 THEN 'Marlène'
				WHEN bp.brand_id = 1164 THEN 'Pauline'
				WHEN bp.brand_id = 405 THEN 'Marlène'
				WHEN bp.brand_id = 2042 THEN 'Lucie'
				WHEN bp.brand_id = 1657 THEN 'Béatrice'
				WHEN bp.brand_id = 2021 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1540 THEN 'Lucie'
				WHEN bp.brand_id = 1853 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 387 THEN 'Pauline'
				WHEN bp.brand_id = 1847 THEN 'Béatrice'
				WHEN bp.brand_id = 2051 THEN 'Iris'
				WHEN bp.brand_id = 1906 THEN 'Emilie'
				WHEN bp.brand_id = 386 THEN 'Iris'
				WHEN bp.brand_id = 1738 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 399
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 399
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 399
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1104 THEN 'Iris'
				WHEN bp.brand_id = 223 THEN 'Marlène'
				WHEN bp.brand_id = 2058 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1501 THEN 'Serpil'
				WHEN bp.brand_id = 1975 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1761
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1761
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 1423 THEN 'Serpil'
				WHEN bp.brand_id = 1932 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1132 THEN 'Léa'
				WHEN bp.brand_id = 1672 THEN 'Béatrice'
				WHEN bp.brand_id = 1512 THEN 'Emilie'
				WHEN bp.brand_id = 346
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 346
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 346
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1848 THEN 'Béatrice'
				WHEN bp.brand_id = 1347 THEN 'Alice'
				WHEN bp.brand_id = 459 THEN 'Alice'
				WHEN bp.brand_id = 2050
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 2050
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 2050
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1892 THEN 'Emilie'
				WHEN bp.brand_id = 1751 THEN 'Alice'
				WHEN bp.brand_id = 1574 THEN 'Béatrice'
				WHEN bp.brand_id = 2006 THEN 'Serpil'
				WHEN bp.brand_id = 2029 THEN 'Iris'
				WHEN bp.brand_id = 1977 THEN 'Léa'
				WHEN bp.brand_id = 1852 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2064 THEN 'Alice'
				WHEN bp.brand_id = 2108 THEN 'Lucie'
				WHEN bp.brand_id = 1491 THEN 'Serpil'
				WHEN bp.brand_id = 2012 THEN 'Emilie'
				WHEN bp.brand_id = 1893 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1762 THEN 'Emilie'
				WHEN bp.brand_id = 1553 THEN 'Léa'
				WHEN bp.brand_id = 1637 THEN 'Emilie'
				WHEN bp.brand_id = 385 THEN 'Iris'
				WHEN bp.brand_id = 1714 THEN 'Serpil'
				WHEN bp.brand_id = 1955 THEN 'Léa'
				WHEN bp.brand_id = 1360 THEN 'Emilie'
				WHEN bp.brand_id = 1587
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1587
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1620 THEN 'Léa'
				WHEN bp.brand_id = 487
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 487
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 496
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 496
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1894 THEN 'Emilie'
				WHEN bp.brand_id = 1426 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1612 THEN 'Serpil'
				WHEN bp.brand_id = 1720 THEN 'Serpil'
				WHEN bp.brand_id = 1898 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1541 THEN 'Anais'
				WHEN bp.brand_id = 1424
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1424
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1545 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1171 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1854 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1833 THEN 'Léa'
				WHEN bp.brand_id = 181
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 181
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1763 THEN 'Emilie'
				WHEN bp.brand_id = 2004 THEN 'Béatrice'
				WHEN bp.brand_id = 2090 THEN 'Marlène'
				WHEN bp.brand_id = 1403 THEN 'Iris'
				WHEN bp.brand_id = 1480 THEN 'Béatrice'
				WHEN bp.brand_id = 1495
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1495
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 2028 THEN 'Lucie'
				WHEN bp.brand_id = 1935 THEN 'Léa'
				WHEN bp.brand_id = 1679 THEN 'Marlène'
				WHEN bp.brand_id = 215 THEN 'Iris'
				WHEN bp.brand_id = 1251 THEN 'Lucie'
				WHEN bp.brand_id = 501 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1596 THEN 'Emilie'
				WHEN bp.brand_id = 2057 THEN 'Lucie'
				WHEN bp.brand_id = 1827 THEN 'Serpil'
				WHEN bp.brand_id = 1568 THEN 'Elodie'
				WHEN bp.brand_id = 2060 THEN 'Marlène'
				WHEN bp.brand_id = 711 THEN 'Alice'
				WHEN bp.brand_id = 2073 THEN 'Emilie'
				WHEN bp.brand_id = 636
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 636
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 1167
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 1167
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1167
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1822 THEN 'Léa'
				WHEN bp.brand_id = 1976 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1733 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1476 THEN 'Léa'
				WHEN bp.brand_id = 1779 THEN 'Marlène'
				WHEN bp.brand_id = 1569 THEN 'Elodie'
				WHEN bp.brand_id = 369 THEN 'Marlène'
				WHEN bp.brand_id = 1421 THEN 'Léa'
				WHEN bp.brand_id = 1524 THEN 'Emilie'
				WHEN bp.brand_id = 1570 THEN 'Léa'
				WHEN bp.brand_id = 1040 THEN 'Alice'
				WHEN bp.brand_id = 1988 THEN 'Marlène'
				WHEN bp.brand_id = 225 THEN 'Alice'
				WHEN bp.brand_id = 1435 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1304 THEN 'Iris'
				WHEN bp.brand_id = 1613 THEN 'Serpil'
				WHEN bp.brand_id = 933 THEN 'Marlène'
				WHEN bp.brand_id = 1473 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1897 THEN 'Emilie'
				WHEN bp.brand_id = 735 THEN 'Emilie'
				WHEN bp.brand_id = 1855 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 143
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 143
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 143
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 395 THEN 'Alice'
				WHEN bp.brand_id = 1393 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 749 THEN 'Lucie'
				WHEN bp.brand_id = 1749 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2043 THEN 'Serpil'
				WHEN bp.brand_id = 1018 THEN 'Emilie'
				WHEN bp.brand_id = 2071 THEN 'Emilie'
				WHEN bp.brand_id = 2033
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 2033
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 475 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1978
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1978
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 2074 THEN 'Léa'
				WHEN bp.brand_id = 1628 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2000 THEN 'Lucie'
				WHEN bp.brand_id = 2059 THEN 'Lucie'
				WHEN bp.brand_id = 2053 THEN 'Serpil'
				WHEN bp.brand_id = 833 THEN 'Serpil'
				WHEN bp.brand_id = 1137 THEN 'Elodie'
				WHEN bp.brand_id = 2107 THEN 'Marlène'
				WHEN bp.brand_id = 1677 THEN 'Lucie'
				WHEN bp.brand_id = 1341 THEN 'Marlène'
				WHEN bp.brand_id = 1752 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1743 THEN 'Léa'
				WHEN bp.brand_id = 1703 THEN 'Marlène'
				WHEN bp.brand_id = 1995 THEN 'Alice'
				WHEN bp.brand_id = 1972 THEN 'Iris'
				WHEN bp.brand_id = 891 THEN 'Iris'
				WHEN bp.brand_id = 1583
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1583
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 967 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1669 THEN 'Léa'
				WHEN bp.brand_id = 1993 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1723 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1484 THEN 'Béatrice'
				WHEN bp.brand_id = 1313 THEN 'Emilie'
				WHEN bp.brand_id = 966 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1127 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1979 THEN 'Léa'
				WHEN bp.brand_id = 473 THEN 'Iris'
				WHEN bp.brand_id = 452
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 452
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1216 THEN 'Emilie'
				WHEN bp.brand_id = 1903 THEN 'Lucie'
				WHEN bp.brand_id = 1912 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1857 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1412 THEN 'Emilie'
				WHEN bp.brand_id = 2054 THEN 'Serpil'
				WHEN bp.brand_id = 1747 THEN 'Léa'
				WHEN bp.brand_id = 1500
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1500
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1199 THEN 'Pauline'
				WHEN bp.brand_id = 1239 THEN 'Léa'
				WHEN bp.brand_id = 2077 THEN 'Elodie'
				WHEN bp.brand_id = 1355 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1907 THEN 'Emilie'
				WHEN bp.brand_id = 1094
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1094
				AND bs.cible = 'BB/Enf/Ado' THEN 'Léa'
				WHEN bp.brand_id = 858 THEN 'Marlène'
				WHEN bp.brand_id = 1764 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1520 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 961 THEN 'Elodie'
				WHEN bp.brand_id = 1617 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1737 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2005 THEN 'Serpil'
				WHEN bp.brand_id = 1990 THEN 'Emilie'
				WHEN bp.brand_id = 323 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1699 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1631 THEN 'Emilie'
				WHEN bp.brand_id = 1486 THEN 'Béatrice'
				WHEN bp.brand_id = 397 THEN 'Léa'
				WHEN bp.brand_id = 777 THEN 'Iris'
				WHEN bp.brand_id = 836 THEN 'Lucie'
				WHEN bp.brand_id = 1863 THEN 'Lucie'
				WHEN bp.brand_id = 599 THEN 'Iris'
				WHEN bp.brand_id = 1371 THEN 'Serpil'
				WHEN bp.brand_id = 1485 THEN 'Béatrice'
				WHEN bp.brand_id = 1356 THEN 'Léa'
				WHEN bp.brand_id = 1107 THEN 'Pauline'
				WHEN bp.brand_id = 2089 THEN 'Marlène'
				WHEN bp.brand_id = 2070 THEN 'Marlène'
				WHEN bp.brand_id = 906 THEN 'Iris'
				WHEN bp.brand_id = 1243 THEN 'Iris'
				WHEN bp.brand_id = 1496
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1496
				AND bs.cible = 'BB/Enf/Ado' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 66
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 66
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1252 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 442
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 442
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1334 THEN 'Marlène'
				WHEN bp.brand_id = 1690 THEN 'Marlène'
				WHEN bp.brand_id = 1226 THEN 'Léa'
				WHEN bp.brand_id = 191 THEN 'Lucie'
				WHEN bp.brand_id = 1362 THEN 'Béatrice'
				WHEN bp.brand_id = 1600 THEN 'Béatrice'
				WHEN bp.brand_id = 1168 THEN 'Lucie'
				WHEN bp.brand_id = 1964 THEN 'Elodie'
				WHEN bp.brand_id = 1147 THEN 'Béatrice'
				WHEN bp.brand_id = 1293 THEN 'Iris'
				WHEN bp.brand_id = 1821 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1858 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2097 THEN 'Béatrice'
				WHEN bp.brand_id = 1363 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1638 THEN 'Emilie'
				WHEN bp.brand_id = 1784 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1765
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1765
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 747 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2091 THEN 'Elodie'
				WHEN bp.brand_id = 1283 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1229
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 1229
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 937 THEN 'Elodie'
				WHEN bp.brand_id = 753 THEN 'Lucie'
				WHEN bp.brand_id = 1335
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 1335
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1488 THEN 'Béatrice'
				WHEN bp.brand_id = 1876 THEN 'Iris'
				WHEN bp.brand_id = 1573 THEN 'Béatrice'
				WHEN bp.brand_id = 440 THEN 'Alice'
				WHEN bp.brand_id = 2061 THEN 'Alice'
				WHEN bp.brand_id = 1987 THEN 'Emilie'
				WHEN bp.brand_id = 1718 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2030 THEN 'Emilie'
				WHEN bp.brand_id = 1303 THEN 'Emilie'
				WHEN bp.brand_id = 1870
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1870
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1233 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1332 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1468 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1391 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 197 THEN 'Lucie'
				WHEN bp.brand_id = 1169
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1169
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1223 THEN 'Iris'
				WHEN bp.brand_id = 570
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 570
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1651 THEN 'Elodie'
				WHEN bp.brand_id = 1542 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1264 THEN 'Iris'
				WHEN bp.brand_id = 1160 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1963 THEN 'Lucie'
				WHEN bp.brand_id = 1425 THEN 'Marlène'
				WHEN bp.brand_id = 1159 THEN 'Elodie'
				WHEN bp.brand_id = 1546 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 800 THEN 'Iris'
				WHEN bp.brand_id = 1299 THEN 'Marlène'
				WHEN bp.brand_id = 1739 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 619
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 619
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 619
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 2105 THEN 'Emilie'
				WHEN bp.brand_id = 177 THEN 'Lucie'
				WHEN bp.brand_id = 1213 THEN 'Béatrice'
				WHEN bp.brand_id = 1726 THEN 'Béatrice'
				WHEN bp.brand_id = 2065 THEN 'Alice'
				WHEN bp.brand_id = 1740 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1849 THEN 'Béatrice'
				WHEN bp.brand_id = 716 THEN 'Lucie'
				WHEN bp.brand_id = 1766 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2027 THEN 'Lucie'
				WHEN bp.brand_id = 2075 THEN 'Anais'
				WHEN bp.brand_id = 1991 THEN 'Léa'
				WHEN bp.brand_id = 402
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 402
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 402
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 512
				AND bs.cible = 'Homme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 512
				AND bs.cible = 'BB/Enf/Ado' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1374 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1778 THEN 'Emilie'
				WHEN bp.brand_id = 2001 THEN 'Lucie'
				WHEN bp.brand_id = 511 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1828 THEN 'Serpil'
				WHEN bp.brand_id = 1639 THEN 'Emilie'
				WHEN bp.brand_id = 1829 THEN 'Serpil'
				WHEN bp.brand_id = 1433
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1433
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1715
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 1715
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1715
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1859 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1490 THEN 'Serpil'
				WHEN bp.brand_id = 1305 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 129 THEN 'Lucie'
				WHEN bp.brand_id = 1536 THEN 'Emilie'
				WHEN bp.brand_id = 1744 THEN 'Léa'
				WHEN bp.brand_id = 1984 THEN 'Serpil'
				WHEN bp.brand_id = 2038 THEN 'Elodie'
				WHEN bp.brand_id = 2035 THEN 'Marlène'
				WHEN bp.brand_id = 1634
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 1634
				AND bs.cible = 'BB/Enf/Ado' THEN 'Léa'
				WHEN bp.brand_id = 1708 THEN 'Béatrice'
				WHEN bp.brand_id = 2024 THEN 'Léa'
				WHEN bp.brand_id = 1788 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1900 THEN 'Léa'
				WHEN bp.brand_id = 1640
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1640
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 1700
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1700
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1046
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 1046
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1046
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1985 THEN 'Emilie'
				WHEN bp.brand_id = 2069 THEN 'Marlène'
				WHEN bp.brand_id = 1957 THEN 'Béatrice'
				WHEN bp.brand_id = 377 THEN 'Alice'
				WHEN bp.brand_id = 1430 THEN 'Serpil'
				WHEN bp.brand_id = 1908
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1908
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 78
				AND bs.cible = 'Femme' THEN 'Pauline'
				WHEN bp.brand_id = 78
				AND bs.cible = 'BB/Enf/Ado' THEN 'Pauline'
				WHEN bp.brand_id = 1661 THEN 'Lucie'
				WHEN bp.brand_id = 79 THEN 'Alice'
				WHEN bp.brand_id = 1152 THEN 'Marlène'
				WHEN bp.brand_id = 1402
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1402
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1981 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1218 THEN 'Lucie'
				WHEN bp.brand_id = 1885 THEN 'Léa'
				WHEN bp.brand_id = 219 THEN 'Alice'
				WHEN bp.brand_id = 479 THEN 'Alice'
				WHEN bp.brand_id = 938 THEN 'Elodie'
				WHEN bp.brand_id = 2052 THEN 'Serpil'
				WHEN bp.brand_id = 1755 THEN 'Alice'
				WHEN bp.brand_id = 1775 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 832
				AND bs.cible = 'Femme' THEN 'Léa'
				WHEN bp.brand_id = 832
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1674 THEN 'Anais'
				WHEN bp.brand_id = 313
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 313
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 313
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1294 THEN 'Marlène'
				WHEN bp.brand_id = 1665 THEN 'Béatrice'
				WHEN bp.brand_id = 1731 THEN 'Elodie'
				WHEN bp.brand_id = 2067 THEN 'Léa'
				WHEN bp.brand_id = 1652 THEN 'Serpil'
				WHEN bp.brand_id = 1416 THEN 'Serpil'
				WHEN bp.brand_id = 530 THEN 'Iris'
				WHEN bp.brand_id = 1713 THEN 'Serpil'
				WHEN bp.brand_id = 1954 THEN 'Léa'
				WHEN bp.brand_id = 1909 THEN 'Emilie'
				WHEN bp.brand_id = 1895 THEN 'Emilie'
				WHEN bp.brand_id = 1292 THEN 'Iris'
				WHEN bp.brand_id = 1350 THEN 'Lucie'
				WHEN bp.brand_id = 1098 THEN 'Emilie'
				WHEN bp.brand_id = 286 THEN 'Alice'
				WHEN bp.brand_id = 1867 THEN 'Lucie'
				WHEN bp.brand_id = 1575 THEN 'Béatrice'
				WHEN bp.brand_id = 1048 THEN 'Elodie'
				WHEN bp.brand_id = 1936 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1204 THEN 'Elodie'
				WHEN bp.brand_id = 1624 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1582 THEN 'Emilie'
				WHEN bp.brand_id = 732
				AND bs.cible = 'Femme' THEN 'Elodie'
				WHEN bp.brand_id = 732
				AND bs.cible = 'BB/Enf/Ado' THEN 'Marlène'
				WHEN bp.brand_id = 1539 THEN 'Emilie'
				WHEN bp.brand_id = 1095 THEN 'Léa'
				WHEN bp.brand_id = 708
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 708
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1242 THEN 'Emilie'
				WHEN bp.brand_id = 1768 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1843 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1502
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 1502
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1577 THEN 'Emilie'
				WHEN bp.brand_id = 1494
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 1494
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1141 THEN 'Léa'
				WHEN bp.brand_id = 324 THEN 'Iris'
				WHEN bp.brand_id = 1983 THEN 'Léa'
				WHEN bp.brand_id = 1475 THEN 'Béatrice'
				WHEN bp.brand_id = 1735 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2055 THEN 'Serpil'
				WHEN bp.brand_id = 546 THEN 'Elodie'
				WHEN bp.brand_id = 1851
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1851
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1712 THEN 'Béatrice'
				WHEN bp.brand_id = 1911 THEN 'Emilie'
				WHEN bp.brand_id = 1958 THEN 'Alice'
				WHEN bp.brand_id = 1878 THEN 'Lucie'
				WHEN bp.brand_id = 85 THEN 'Lucie'
				WHEN bp.brand_id = 1992 THEN 'Léa'
				WHEN bp.brand_id = 1417 THEN 'Béatrice'
				WHEN bp.brand_id = 2002 THEN 'Lucie'
				WHEN bp.brand_id = 1901 THEN 'Léa'
				WHEN bp.brand_id = 1560 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 310 THEN 'Elodie'
				WHEN bp.brand_id = 319 THEN 'Lucie'
				WHEN bp.brand_id = 1344 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 270 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1054 THEN 'Marlène'
				WHEN bp.brand_id = 2098 THEN 'Béatrice'
				WHEN bp.brand_id = 320
				AND bs.cible = 'Femme' THEN 'Alice'
				WHEN bp.brand_id = 320
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 320
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1891 THEN 'Emilie'
				WHEN bp.brand_id = 111 THEN 'Alice'
				WHEN bp.brand_id = 1474 THEN 'Béatrice'
				WHEN bp.brand_id = 1308 THEN 'Béatrice'
				WHEN bp.brand_id = 1194 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 199 THEN 'Lucie'
				WHEN bp.brand_id = 1846 THEN 'Béatrice'
				WHEN bp.brand_id = 2015 THEN 'Elodie'
				WHEN bp.brand_id = 1994 THEN 'Emilie'
				WHEN bp.brand_id = 1031 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1302 THEN 'Iris'
				WHEN bp.brand_id = 1138 THEN 'Marlène'
				WHEN bp.brand_id = 2096 THEN 'Emilie'
				WHEN bp.brand_id = 370 THEN 'Iris'
				WHEN bp.brand_id = 381 THEN 'Iris'
				WHEN bp.brand_id = 1884 THEN 'Serpil'
				WHEN bp.brand_id = 559 THEN 'Alice'
				WHEN bp.brand_id = 1728 THEN 'Lucie'
				WHEN bp.brand_id = 1135 THEN 'Elodie'
				WHEN bp.brand_id = 1860 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1982 THEN 'Léa'
				WHEN bp.brand_id = 1419
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 1419
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1531 THEN 'Léa'
				WHEN bp.brand_id = 483 THEN 'Marlène'
				WHEN bp.brand_id = 303 THEN 'Alice'
				WHEN bp.brand_id = 1769
				AND bs.cible = 'Homme' THEN 'Alice'
				WHEN bp.brand_id = 1769
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 721 THEN 'Lucie'
				WHEN bp.brand_id = 1770 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2081 THEN 'Béatrice'
				WHEN bp.brand_id = 589 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1980 THEN 'Béatrice'
				WHEN bp.brand_id = 2078 THEN 'Marlène'
				WHEN bp.brand_id = 1214
				AND bs.cible = 'Femme' THEN 'Béatrice'
				WHEN bp.brand_id = 1214
				AND bs.cible = 'BB/Enf/Ado' THEN 'Lucie'
				WHEN bp.brand_id = 489
				AND bs.cible = 'Femme' THEN 'Serpil'
				WHEN bp.brand_id = 489
				AND bs.cible = 'Homme' THEN 'Serpil'
				WHEN bp.brand_id = 489
				AND bs.cible = 'BB/Enf/Ado' THEN 'Iris'
				WHEN bp.brand_id = 1340 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1678 THEN 'Marlène'
				WHEN bp.brand_id = 1478 THEN 'Anais'
				WHEN bp.brand_id = 1704
				AND bs.cible = 'Femme' THEN 'Emilie'
				WHEN bp.brand_id = 1704
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1861 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 404 THEN 'Alice'
				WHEN bp.brand_id = 1358 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1558 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 809 THEN 'Léa'
				WHEN bp.brand_id = 1013
				AND bs.cible = 'Femme' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1013
				AND bs.cible = 'BB/Enf/Ado' THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 893 THEN 'Lucie'
				WHEN bp.brand_id = 1450 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1864 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 2092 THEN 'Elodie'
				WHEN bp.brand_id = 2039 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1989 THEN 'Lucie'
				WHEN bp.brand_id = 1721 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 336
				AND bs.cible = 'Homme' THEN 'Alice'
				WHEN bp.brand_id = 336
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1301 THEN 'Elodie'
				WHEN bp.brand_id = 1830 THEN 'Serpil'
				WHEN bp.brand_id = 1879 THEN 'Marlène'
				WHEN bp.brand_id = 2011 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1750 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1099 THEN 'Elodie'
				WHEN bp.brand_id = 262
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 262
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1841 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 180
				AND bs.cible = 'Homme' THEN 'Emilie'
				WHEN bp.brand_id = 180
				AND bs.cible = 'BB/Enf/Ado' THEN 'Alice'
				WHEN bp.brand_id = 1719 THEN 'Serpil'
				WHEN bp.brand_id = 1359 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1705 THEN 'Alice'
				WHEN bp.brand_id = 1711 THEN 'Elodie'
				WHEN bp.brand_id = 1145 THEN 'Lucie'
				WHEN bp.brand_id = 1222 THEN 'Lucie'
				WHEN bp.brand_id = 1882 THEN 'Lucie'
				WHEN bp.brand_id = 2076 THEN 'Serpil'
				WHEN bp.brand_id = 1258 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1594 THEN 'Serpil'
				WHEN bp.brand_id = 1996 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1241 THEN 'Elodie'
				WHEN bp.brand_id = 857 THEN 'Lucie'
				WHEN bp.brand_id = 1691 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1011 THEN 'Acheteur.se Junior Accessoires'
				WHEN bp.brand_id = 1187 THEN 'Serpil'
				WHEN bp.brand_id = 1794 THEN 'Marlène'
				WHEN bp.brand_id = 606 THEN 'Alice'
				WHEN bp.brand_id = 1525 THEN 'Anais'
				WHEN bp.brand_id = 1883 THEN 'Lucie'
				WHEN bp.brand_id = 1151 THEN 'Marlène'
				WHEN bp.brand_id = 1961 THEN 'Béatrice'
				WHEN bp.brand_id = 1664 THEN 'Léa'
			END AS buyer,
			bs.univers AS univers,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') THEN sn.stock_n ELSE NULL END) AS stock_pe23_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') THEN sn.stock_n ELSE NULL END) AS stock_pe23_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') THEN sn1.stock_n1 ELSE NULL END) AS stock_pe22_perm,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') THEN sn1.stock_n1 ELSE NULL END) AS stock_pe22_saiso,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') THEN sn.stock_n * bs.paht / 10000 ELSE NULL END) AS stock_pe23_perm_valo,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE23') THEN sn.stock_n * bs.paht / 10000 ELSE NULL END) AS stock_pe23_saiso_valo,
			sum(CASE WHEN bp.saison LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') THEN sn1.stock_n1 * bs.paht / 10000 ELSE NULL END) AS stock_pe22_perm_valo,
			sum(CASE WHEN bp.saison NOT LIKE 'Perm%' AND bp.product_id IN (SELECT pid FROM saison WHERE s = 'PE22') THEN sn1.stock_n1 * bs.paht / 10000 ELSE NULL END) AS stock_pe22_saiso_valo
		FROM
			smallable2_datawarehouse.b_products bp
		INNER JOIN smallable2_datawarehouse.b_skus bs ON
			bs.product_id = bp.product_id
		LEFT JOIN stock_n sn ON
			sn.s = bs.sku_id
		LEFT JOIN stock_n1 sn1 ON
			sn1.s = bs.sku_id
		WHERE
			bp.sml_team = 'mode'
			AND bs.univers NOT IN ('Masques', 'na')
				AND bs.personne_ordre != 'na'
			GROUP BY
				personne,
				marque,
				buyer,
				univers
			ORDER BY
				personne ASC,
				marque ASC) s ON
	v.personne || v.marque || v.buyer || v.univers = s.personne || s.marque || s.buyer || s.univers
WHERE
	v.buyer IS NOT NULL 
